In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [7]:
np.asarray([1,2,4])

array([1, 2, 4])

In [8]:
a = [1,2,4]

In [9]:
np.asanyarray(a)

array([1, 2, 4])

In [10]:
b = np.matrix([[1,2],[2,3]])

In [11]:
b

matrix([[1, 2],
        [2, 3]])

In [12]:
c = b

In [13]:
a

[1, 2, 4]

In [14]:
c

matrix([[1, 2],
        [2, 3]])

In [15]:
b

matrix([[1, 2],
        [2, 3]])

In [16]:
c[0][0]

matrix([[1, 2]])

In [17]:
c[0]

matrix([[1, 2]])

In [18]:
d = np.copy(c)

In [19]:
d

array([[1, 2],
       [2, 3]])

In [23]:
d[0] = [8,0]

In [24]:
d

array([[8, 0],
       [2, 3]])

In [25]:
c

matrix([[1, 2],
        [2, 3]])

In [26]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
iter = (i*i for i in range(5))

In [29]:
np.fromiter(iter,float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring("223 224 225", sep=" ")

array([223., 224., 225.])

Datatype in numpy

In [31]:
l = [1,2,3]

In [32]:
ar = np.array(l)

In [34]:
ar.ndim

1

In [35]:
ar.size

3

In [36]:
ar.shape

(3,)

In [37]:
br = np.array([[1,2], [2,3]])

In [39]:
br.shape

(2, 2)

In [40]:
br.dtype

dtype('int32')

In [41]:
br

array([[1, 2],
       [2, 3]])

In [42]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
np.a